#! /usr/bin/python

# backup tool
# irfan

import sys
import os
import time
import getpass
import tarfile
import paramiko

def usage():
  """ print usage informaton """
  print "usage: host tag paths"

def main(argv):
  if not argv:
    usage()
    return
  begin_archive(argv)


def create_archive(arch_name, paths):

  print "using archive:", arch_name,"..."
  print "using paths:",":".join(paths),"..."

  tar = tarfile.open(arch_name, "w")

  return tar,paths


def begin_archive(argv):
  arch_file_name = argv[0] + "_" + argv[1] + "_" + str(time.time()) + ".tar.gz"
  tar, paths = create_archive(arch_file_name, argv[2:])

  do_archive(argv[0],tar,paths)

  return

def do_archive(host, tar, paths):

  print "connecting to host:",host + "."
  ssh_client = paramiko.SSHClient()
  ssh_client.set_missing_host_key_policy(paramiko.AutoAddPolicy())

  print "--------------------"
  print "using user:", os.environ['USER']
  if os.getenv('PARAMIKO_PASS') is None:
    print "we will try your login password or your ssh key.."
    pass_in = getpass.getpass("provide pass for user|key:")
  else:
    pass_in = os.environ['PARAMIKO_PASS']
  print "--------------------"

  ssh_client.connect(host, 22, os.environ['USER'], pass_in)

  return


if __name__ == "__main__":
    main(sys.argv[1:])


