#! /usr/bin/python

# backup tool
# irfan

import sys
import os
import time
import getpass
import paramiko

def usage():
  """ print usage informaton """
  print "usage: host tag paths"

def main(argv):
  if not argv:
    usage()
    return
  if len(argv) < 3:
    usage()
    return

  begin_archive(argv)

class bcolors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'

def create_archive(arch_name, paths):

  print bcolors.OKGREEN + "using archive:" + bcolors.ENDC, arch_name,"..."
  print bcolors.OKGREEN + "using paths:" + bcolors.ENDC, ":".join(paths),"..."

  return paths


def begin_archive(argv):
  arch_file_name = argv[0] + "_" + argv[1] + "_" + str(time.time()) + ".tar.gz"
  paths = create_archive(arch_file_name, argv[2:])

  do_archive(argv[0],paths, arch_file_name)

  return


def do_archive(host, paths, archive_name):

  print bcolors.WARNING + "connecting to host:" + bcolors.ENDC,host + "."
  ssh_client = paramiko.SSHClient()
  ssh_client.set_missing_host_key_policy(paramiko.AutoAddPolicy())

  print "--------------------"
  print "using user:", os.environ['USER']
  if os.getenv('PARAMIKO_PASS') is None:
    print "we will try your login password or your ssh key.."
    pass_in = getpass.getpass("provide pass for user|key:")
  else:
    pass_in = os.environ['PARAMIKO_PASS']
  print "--------------------"

  try:
    ssh_client.connect(host, 22, os.environ['USER'], pass_in)
  except:
    print "Error with SSH connection"
    return

  sudo_pass_in = getpass.getpass("sudo password:")

  # begin processing remote files
  for p in paths:
    print bcolors.OKGREEN + "processing path:" + bcolors.ENDC ,p,"..."
    stdin, stdout, stderr = ssh_client.exec_command("sudo -S find " + p + " -type f -name \"*.*\" -print -exec tar -rf " + archive_name + " {} \;", get_pty=True)
    stdin.write(sudo_pass_in + "\n")
    stdin.flush()

  try:
    # begin transfering archive
    sftp_client = ssh_client.open_sftp()
    sftp_client.get(archive_name, archive_name)

    bytes_tx = os.path.getsize(archive_name)
    if bytes_tx == 0:
        print bcolors.WARNING + archive_name,"is zero bytes :( -- error?" + bcolors.ENDC
    else:
        print bcolors.OKBLUE + "transfered",bytes_tx,"bytes" + bcolors.ENDC

    # clean-up archive
    stdin, stdout, stderr = ssh_client.exec_command("rm " + archive_name)
  except:
      print bcolors.FAIL + archive_name,"backup :( -- error?" + bcolors.ENDC
    
  return


if __name__ == "__main__":
    main(sys.argv[1:])


